[project]
name = "lampe-review"
version = "0.1.0"
description = "Review package for lampe-sdk"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

# NOTE: This is needed, because the folder under src isn't lampe_review
# as expected by the default hatchling build system.
[tool.hatch.build.targets.wheel]
packages = ["src/lampe"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
